### ISSUE TITLE
Command isn't passed to sudo

### ISSUE THREAD

**Issue by evertonstz** [mdeboer/zsh-plugin-appup#3]
My docker runs under root, therefore I have to use composer to run things with sudo, the problem is that when I try to "sudo up" the up command isn't passed to sudo, it returns a command not found. I can run "up" without sude fine tho.

**Comment by mdeboer** [comment]
Sorry for my very late reply! I can't really help you with that as this is a `sudo` related issue and not specific for my plugin.

Please see https://unix.stackexchange.com/questions/317687/command-not-found-when-sudoing-function-from-zshrc for an answer on this. Good luck!
