### ISSUE TITLE
Parse error on new installation

### ISSUE THREAD

**Issue by minchinweb** [mdeboer/zsh-plugin-appup#5]
I followed the git clone command, added it to my plugins in `.zshrc`, but when I reload my profile (`source .zshrc`) it gives me an error:

```
~/.oh-my-zsh/custom/plugins/appup/appup.plugin.zsh:49: parse error near `elif'
```

I'm in my home directory, so there isn't a docker-compose (or vagrant file) in this directory.

**Comment by mdeboer** [comment]
It is probably waaaay too late to respond to your issue but I hope you still use my plugin and that it's all working now. A lot has changed in the meanwhile and I can't reproduce the issue.
